### ISSUE TITLE
Conda environment template file

### ISSUE THREAD

**Issue by ccbaumler** [sourmash-bio/sourmash_plugin_branchwater#127]
To run `pyo3_branchwater` in a conda environment, I needed the  `gcc_linux-64` and `gxx_linux-64` conda packages to run the plugin.

```
cat envs/sourmash-dev.yaml

channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - python>=3.8,<3.10
 - sourmash>=4.8.0,<5
 - rust
 - gcc_linux-64
 - gxx_linux-64
 - pip
 - pip:
   - sourmash-mixers
   - git+https://github.com/sourmash-bio/pyo3_branchwater.git#egg=pyo3_branchwater
```

**Comment by ctb** [comment]
oh, interesting! You shouldn't need the compilers but rather only the runtime libraries; and also the gcc and gxx stuff should probably be `compilers`. But all things to check and confirm.

We should add this to: https://github.com/sourmash-bio/pyo3_branchwater/blob/main/environment.yml

and figure out what is needed for compilation vs runtime...

thanks!

**Comment by ctb** [comment]
Observed again in #148. And fixed, we hope, by #151.

The question is, what things from `compilers` do we need to _build_ pyo3_branchwater, vs what is needed to _run_ it? They should be different - you shouldn't need all of compilers to run the darn thing!

I think this could be tested by creating the two conda environments, and in the build environment building a wheel, and then installing the wheel in the runtime environment.

**Comment by ctb** [comment]
I verified that the new environment.yaml file worked on our Linux system, `farm` - with one exception. We also needed `patchelf` in the environment.

Creating a conda environment from the following `runtime.yaml` worked fine for the wheel built in the latest `environment.yml`.

runtime.yaml:
```
name: branchwater-dev
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - sourmash>=4.8.3,<5
    - pandas
```

**Comment by ctb** [comment]
Closing this now that conda-forge installation is working :)
