### ISSUE TITLE
Crash with sourmash manysketch with very large (2 billion row+) datasets

### ISSUE THREAD

**Issue by mnapolitano89** [sourmash-bio/sourmash_plugin_branchwater#147]
Hello, 
I was using manysketch on a large dataset, and noticed that on the manifest writing step, it crashed saying that zipwriter was already closed. Doing some digging, I think the issue is that the options for zip::write::FileOptions uses the default large file setting (false) here https://github.com/sourmash-bio/pyo3_branchwater/blob/3f1994365c40d57c1fc3d6040b4bd5d2e8c8f5e2/src/utils.rs#L1019 
which causes an exception to get thrown if the zip file ends up being over 4gb (https://docs.rs/zip/latest/zip/write/struct.FileOptions.html#method.large_file). Setting options to `zip::write::FileOptions::default().compression_method(zip::CompressionMethod::Stored).large_file(true);` seems to have fixed the issue

**Comment by bluegenes** [comment]
Thanks @mnapolitano89! 

for our ref: https://strawlab.org/strand-braid-api-docs/latest/zip/write/struct.FileOptions.html#method.large_file

<img width="723" alt="image" src="https://github.com/sourmash-bio/sourmash_plugin_branchwater/assets/7740734/933bf213-7168-4f21-a623-e1c313da0f2e">
