### ISSUE TITLE
Cool with custom channel anaconda release?

### ISSUE THREAD

**Issue by dkoslicki** [sourmash-bio/sourmash_plugin_branchwater#152]
Hi @ctb , @bluegenes and others! We'd (@chunyuma) like to publish [YACHT](https://github.com/KoslickiLab/YACHT) to conda and it uses a specific commit of branchwater as a dependency. However, conda doesn't like that the way we're currently using pip, and it was recommended to us to make a conda release of branchwater in a custom channel. Are y'all ok with this? We'd make sure to clearly indicate the brancheater in this custom channel is meant _only_ for installing YACHT.

**Comment by ctb** [comment]
A few quick thoughts -

* [looks like](https://github.com/KoslickiLab/YACHT/blob/main/env/yacht_env.yml) you're using version 0.8.1, not a specific commit - excellent!
* I am OK with a conda release of branchwater for a custom channel, but I don't know if or how that will mess things up when we (sooner? later?) post branchwater on conda-forge. @luizirber any thoughts on a good short-term solution here? I'm thinking maybe if you name it something other than 'branchwater' that might avoid future problems?

thank you for checking!

**Comment by dkoslicki** [comment]
Thanks! We’ll wait to hear from @luizirber before pursuing a bioconda release in a custom channel. Looks like the most straightforward way in the time-being is a post-install pip script. We’ll use that until a full conda approach becomes feasible and/or you all release branchwater to conda

**Comment by ctb** [comment]
seeing if maybe we can just build a conda-forge recipe for branchwater - trial run [here](https://github.com/conda-forge/staged-recipes/pull/24530)

**Comment by luizirber** [comment]
> seeing if maybe we can just build a conda-forge recipe for branchwater - trial run [here](https://github.com/conda-forge/staged-recipes/pull/24530)

Yup, that was going to be my suggestion! `conda-forge` is upstream of `bioconda` (and required to use it properly), so it is already in the channel list. Another custom channel would still be hard to distribute [^1], and conda-forge allows more customization (like extra archs) that bioconda doesn't support, which makes more sense for non-pure Python packages.

[^1]: it is already hard to get people to setup bioconda+conda-forge properly :sweat_smile:

**Comment by ctb** [comment]
whoo! linux build worked!

**Comment by dkoslicki** [comment]
Awesome! Let us know if we can help at all with getting it on conda-forge (eg. @ctb I have folks who may be able to help with the [recipe](https://github.com/conda-forge/staged-recipes/pull/24530))! Our YACHT conda release is blocking on branchwater, so we're rather motivated to help! :)

**Comment by ctb** [comment]
heads up - per https://github.com/sourmash-bio/pyo3_branchwater/issues/17, we're renaming to `sourmash_plugin_branchwater` over in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/156

**Comment by ctb** [comment]
hi @dkoslicki I put through the rename and got the Linux build working. Unfortunately, I'm out of time to work on it intensively today (and probably tomorrow). SO, if you & yours would like to help that would be lovely!

The two thoughts I had -
* we could _just_ support Linux for now, if that would work for you - and if so, I could use guidance on how to disable win/osx builds. 
* alternatively, OS X support would be fantastic, but that build is not working right now. So help getting that build working would be fantastic! 

Probably the easiest would be to just submit PRs into my branch, the source branch [here](https://github.com/conda-forge/staged-recipes/pull/24530), and I can merge them quickly - I have time today, just not big chunks.

**Comment by ctb** [comment]
The linux-only build seems to have worked. Shall I put the PR up for merge or do we want to try to get OS X to work first? @luizirber @dkoslicki @bluegenes

**Comment by ctb** [comment]
https://github.com/conda-forge/staged-recipes/pull/24530 merged! I'll close this issue (and open a new one about `win` and `osx` targets) once I confirm that install from conda-forge is working.

**Comment by ctb** [comment]
progress! https://github.com/conda-forge/sourmash_plugin_branchwater-feedstock/commit/3ff1132deb93996fb35da49ff2f6ce6aa1fc5b57#commitcomment-134263657

**Comment by dkoslicki** [comment]
Whoot! I just noticed it's officially available on conda-forge now. Thanks @ctb !

**Comment by ctb** [comment]
Yep, and looks like it all works!

```
% mamba create -n branch-test-dec5 -y sourmash_plugin_branchwater sourmash
% mamba activate activate branch-test-dec-5
% sourmash scripts

== This is sourmash version 4.8.4. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

options:
  -h, --help  show this help message and exit

available plugin/extension commands:
  sourmash scripts manysearch       - search many metagenomes for contained genomes
  sourmash scripts multisearch      - massively parallel in-memory sketch search
  sourmash scripts fastgather       - massively parallel sketch gather
  sourmash scripts fastmultigather  - massively parallel sketch multigather
  sourmash scripts index            - Build Branchwater RevIndex
  sourmash scripts check            - Check Branchwater RevIndex
  sourmash scripts manysketch       - massively parallel sketching
```

Let us know if you run into any problems building on top of this - excited to see YACHT out there!

**Comment by ctb** [comment]
closing in favor of https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/160 for future work!

**Comment by ctb** [comment]
> We've been having a heck of a time getting OS X to work, mainly due to bioconda moving to Azure, it looks like their build system is missing a necessary clang lib to compile Rust stuff. I'd vote just go with linux for the time being as we pursue the missing lib issue in the bioconda Gitter channel.

so @luizirber got sourmash-minimal [working on conda-forge](https://github.com/conda-forge/sourmash-minimal-feedstock/pull/55), and I copied his approach in https://github.com/conda-forge/sourmash_plugin_branchwater-feedstock/pull/3 - so both sourmash-minimal and branchwater should be working on MacOS now!

**Comment by dkoslicki** [comment]
Awesome, thanks for the update! That looked rather nontrivial to do!
