### ISSUE TITLE
Calculate ANI based on a CLI flag

### ISSUE THREAD

**Issue by mr-eyes** [sourmash-bio/sourmash_plugin_branchwater#164]
I think incorporating ANI calculation in the branchwater plugin will be very useful. For performance, the code will need to be rewritten in Rust, though.

**Comment by mr-eyes** [comment]
Hi @ctb and @bluegenes 

I wrote a Rust implementation of the sourmash ANI estimation code many weeks ago but never committed it https://github.com/sourmash-bio/sourmash_plugin_branchwater/commit/3b1c1b887fa128556c8bd5bc849be81a53a28969

Just putting it here for now in case it's useful until I can continue the integration later, or maybe someone faster than me will do.

The Rust implementation is **712X** faster than the original Python implementation.

**Comment by ctb** [comment]
> The Rust implementation is **712X** faster than the original Python implementation.

not good enough. Do better.

😆 that's awesome!

**Comment by ctb** [comment]
> Let's coauthor a PR to add this to all commands (I hope you do the testing 😂).

🤔

**Comment by mr-eyes** [comment]
> > Let's coauthor a PR to add this to all commands (I hope you do the testing 😂).
> 
> 🤔

I am not very skilled at writing tests in sourmash because it requires a broader context that I am not very familiar with.

**Comment by bluegenes** [comment]
Streamlined `ANI` from https://github.com/sourmash-bio/sourmash/pull/2943 seems to be 2x faster than this rust implementation, as it doesn't cause a 2x slowdown compared to _not_ calculating ANI :) 

comparison benchmark (ANI vs not): https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/236#issuecomment-1962735930

**Comment by ctb** [comment]
Remaining functionality added in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/298 and https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/361. ANI should now be available everywhere ;)
