### ISSUE TITLE
rename package

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash_plugin_branchwater#17]
maybe ... branchwater-py?

**Comment by ctb** [comment]
or just `branchwater_plugin`?

it turns out to be difficult to have it be named something different from the Rust package. So maybe `branchwater-py` is better.

**Comment by ctb** [comment]
or just `branchwater`?

**Comment by luizirber** [comment]
> or just `branchwater`?

that kind of takes ownership of the whole namespace for a plugin, which might make it harder later to manage the multiple things named branchwater ([branchwater-web](https://github.com/sourmash-bio/branchwater-web), [mastiff](https://github.com/sourmash-bio/mastiff) [^1]) in the future.

So maybe a name that keeps clear this is a sourmash plugin?

[^1]: need to rename it, after we agreed to go with everything being named branchwater

**Comment by ctb** [comment]
I've been naming other plugins `sourmash_plugin_x` so `sourmash_plugin_branchwater` would be consistent with that.

Or `sourmash-branchwater-plugin`...?

Meh. I'll rename to `sourmash_plugin_branchwater` in a few days unless someone objects ;)

**Comment by ctb** [comment]
Renaming over in #156
