### ISSUE TITLE
optionally enable full `gather` csv output from `fastmultigather`

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash_plugin_branchwater#187]
after #134, I was hoping to provide all gather columns in the branchwater fastmultigather results csv by using the rust `GatherResult` and adding in the query-specific columns within branchwater.

I think that's feasible, but might require a little more work in rust core:

- `disk_revindex.rs`: need to populate remaining `GatherResult` cols https://github.com/sourmash-bio/sourmash/blob/latest/src/core/src/index/revindex/disk_revindex.rs#L327-L334

- `linear.rs`: need to populate remaining `GatherResult` cols https://github.com/sourmash-bio/sourmash/blob/ccb1d491807767ab9d3c9b005ff21ac953c34883/src/core/src/index/linear.rs#L186-L193
- `mem_revindex.rs`: is this actually using `GatherResult`? https://github.com/sourmash-bio/sourmash/blob/latest/src/core/src/index/revindex/mem_revindex.rs#L201-L233

Ref:
- rust `GatherResult`: https://github.com/sourmash-bio/sourmash/blob/ccb1d491807767ab9d3c9b005ff21ac953c34883/src/core/src/index/mod.rs#L27-L59

- python `GatherResult` (all columns needed for output file parity). Tthe query-specific ones could/should remain outside of the rust `GatherResult`, since they're just extra info that help us later, once we no longer have access to the query sketch. https://github.com/sourmash-bio/sourmash/blob/ccb1d491807767ab9d3c9b005ff21ac953c34883/src/sourmash/search.py#L428

> As noted in https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/107, we need to be wary of performance hits as a result of calculating the additional columns. We might want to make lightweight version default, and support an option for calculating + outputting the full csv (or vice versa)

**Comment by ctb** [comment]
or we could shortcut!

https://github.com/ctb/2024-calc-full-gather

**Comment by ctb** [comment]
So a few lessons from calc-full-gather - basically, calc-full-gather works with fastgather results, but not with fastmultigather results. This is because fastmultigather for various reasons doesn't have the same columns as fastgather. SIGH.

Ref https://github.com/ctb/2024-calc-full-gather/issues/2
