### ISSUE TITLE
ksize does not reflect parameters for protein from sourmash scripts manysketch when running sourmash sig summary 

### ISSUE THREAD

**Issue by jsrdrgz** [sourmash-bio/sourmash_plugin_branchwater#216]
I am sketching multiple files where some are DNA and others are protein, so I also have different sizes:
```sourmash scripts manysketch datasets.csv -p k=15,k=21,k=27,k=33,scaled=1 -p protein,k=5,k=7,k=9,k=11,scaled=1 -c 4 -o manysketch.zip```

log output reflects these parameters (which is great): 

```
== This is sourmash version 4.8.6. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

=> sourmash_plugin_branchwater 0.8.6; cite Irber et al., doi: 10.1101/2022.11.02.514947

params: ['k=15,k=21,k=27,k=33,scaled=1', 'protein,k=5,k=7,k=9,k=11,scaled=1']
sketching all files in 'datasets.csv' using 4 threads
Loaded 2 rows in total (2 genome and 2 protein files)
Starting file 1/4 (25%)
Starting file 4/4 (100%)
Starting file 2/4 (50%)
Starting file 3/4 (75%)
Writing manifest
DONE. Processed 4 fasta files
...manysketch is done! results in 'manysketch.zip'
```

But when obtaining a summary from the resulting zip file, it is confusing.

```sourmash sig summarize manysketch.zip```

The ksizes that I used for protein are not reflected in the summary.

```
== This is sourmash version 4.8.6. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

** loading from 'manysketch.zip'
path filetype: ZipFileLinearIndex
location: /data/jzr5814/repositories/dnds-using-fmh/src/demo/branchwater/manysketch.zip
is database? yes
has manifest? yes
num signatures: 16
** examining manifest...
total hashes: 125538
summary of sketches:
   2 sketches with protein, k=21, scaled=1            7632 total hashes
   2 sketches with protein, k=15, scaled=1            7285 total hashes
   2 sketches with protein, k=33, scaled=1            8236 total hashes
   2 sketches with protein, k=27, scaled=1            7943 total hashes
   2 sketches with DNA, k=27, scaled=1                24134 total hashes
   2 sketches with DNA, k=21, scaled=1                23164 total hashes
   2 sketches with DNA, k=15, scaled=1                22105 total hashes
   2 sketches with DNA, k=33, scaled=1                25039 total hashes
```

**Comment by bluegenes** [comment]
Thanks for finding this bug @jsrdrgz!

The reason for this is that protein k-mer sizes are k=k*3 internally (legacy sourmash reasons), and we currently fail to return to the original ksizes prior to writing the zipfile manifest. This means the signatures were made at the right size, but the incorrect manifest might impact signature selection for comparisons -- sorry about that. I'll submit a fix.

for me: relevant line here: https://github.com/sourmash-bio/sourmash_plugin_branchwater/blob/main/src/utils.rs#L786

**Comment by bluegenes** [comment]
hi @jsrdrgz - fix is in release v0.9.0. Give it a try and let us know!

**Comment by ctb** [comment]
(v0.90. isn't yet posted on conda - if that's how you're installing it, please wait, I'll let you know when it's up!)

**Comment by jsrdrgz** [comment]
I'll wait for conda! Thank you so much!

**Comment by ctb** [comment]
It's up! Testing it now myself ;)

**Comment by jsrdrgz** [comment]
Works on my end! Thank you for being awesome!
