### ISSUE TITLE
what query and against types does `manysearch` actually support?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash_plugin_branchwater#232]
running into problems using zip files as queries, and other things. need to look into this!

**Comment by ctb** [comment]
I poked around a bit and I absolutely do not understand what is going on 😆 . So, you know, please hold...

**Comment by ctb** [comment]
it looks like my `podar-ref.zip` file is wonky in some way. Digging.

**Comment by ctb** [comment]
ah-hah! it looks like zip files _must_ contain a manifest, and if they don't, branchwater barfs and tries to read it as a pathlist or something.

**Comment by bluegenes** [comment]
> ah-hah! it looks like zip files must contain a manifest, and if they don't, branchwater barfs and tries to read it as a pathlist or something.

this makes sense. I just assumed all zips would have manifests and didn't do any special handling otherwise.

**Comment by ctb** [comment]
spent some time tracking this down over in https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/237 - looks like zip files cannot be loaded from either pathlists or manifests.

**Comment by ctb** [comment]
we might _also_ want to support traversing zip files without manifests. Or (probably better!) more politely erroring out if zip files don't contain a manifest.

**Comment by ctb** [comment]
closing in favor of https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/264 and https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/266
