### ISSUE TITLE
`fastgather` CSV output for `intersect_bp` is in hashes, not in hashes * scaled as it is in `sourmash gather` output

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash_plugin_branchwater#254]
we should match sourmash output where possible.

**Comment by bluegenes** [comment]
So we currently calculate via `intersect_bp: best_element.overlap`, which is actually the uniquely intersected hashes. So `best_element.overlap * scaled` would be `unique_intersect_bp`.

options:
- change the column name,
- change to calculate general intersect_bp
- add `unique_intersect_bp` column and calculate both.

**Comment by ctb** [comment]
I think: replace column with `unique_intersect_bp` calculated as in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/298. My suspicion is we should just be using `--full-results` by default anyway, yah? See [my comment](https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/298#issuecomment-2094141407).

**Comment by bluegenes** [comment]
right -- now that full results are default, #298 handles both `intersect_bp` and `unique_intersect_bp`.

We match all sourmash columns except: 
- `match_name` instead of gather `name`
- `match_filename` instead of gather `filename`
- `match_md5` instead of gather `md5`
