### ISSUE TITLE
allow search against multiple databases?

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash_plugin_branchwater#263]
sourmash commands allow search / gather across multiple databases. We could enable that here too.

**Comment by ctb** [comment]
hot take: we could provide this with standalone manifests, instead of complicating the command line - viz https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/235

**Comment by ctb** [comment]
Support for this is being added in #430.

**Comment by ctb** [comment]
#430 is merged and released in v0.9.8.
