### ISSUE TITLE
full gather results from plugin are not compatible with `sourmash tax`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash_plugin_branchwater#330]
Now that https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/298 was merged, we can in theory use the full gather results from `fastgather` and `fastmultigather` for taxonomy reporting with `sourmash tax metagenome`.

But... not so fast!

It looks like there are incompatibilities. I'm getting `ERROR: Error: Cannot add TaxResult: query information does not match.` when running (e.g.) `sourmash tax metagenome -t ../sourmash/gtdb-rs214.lineages.sqldb -g srr.fg.csv`.

I debugged it a little this morning - the QueryInfo comparison in `is_compatible` in `tax/tax_utils.py` seems to be failing.

I'm not sure how much of it is the different column names vs other things, but I think we need to resolve this before a release.

cc @bluegenes - no good deed goes unpunished 😆 😭

**Comment by bluegenes** [comment]
Hmm, the changed cols are all match related, and this error looks like it's the related to the query columns (query_name, query_md5, query_bp, etc). All query columns should be identical for a single query, and should not reflect any subtraction  we do during gather.

Can you select query cols and sort uniq to see if any change across the file? Or point me at your file? :)

**Comment by ctb** [comment]
ref #331 also

just try to use the `srr.fg.csv` file in the repo https://github.com/ctb/2024-debug-gather-difference.

(gotta run, more later maybe?)

**Comment by ctb** [comment]
Fixed by https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/353
