### ISSUE TITLE
sourmash fastgather -> tax

### ISSUE THREAD

**Issue by AnneliektH** [sourmash-bio/sourmash_plugin_branchwater#386]
Hey I ran fastgather to tax: 
fastgather results are in `/group/ctbrowngrp2/scratch/annie/2024-pigparadigm/results/sourmash/fastgather`
tax results are in `/group/ctbrowngrp2/scratch/annie/2024-pigparadigm/results/sourmash/fastgather/tax`

Using wort-data signatures, gtdb-214-reps db.

Ran as follows:
`sourmash scripts fastgather {input.sig} {GTDB} 
-k 21 --scaled 1000 -c {threads} -o {output.csv}`

`sourmash tax annotate -g {input.csv} -t {GTDB_TAX} 
-o ../results/sourmash/fastgather/ > {output.csv}`

Gives me taxonomic classifications, but not taxonomic ranks in the output csv. 
Rank is now just a list of numbers, that is as long as the number of matches. 
I would like to select matches with a certain tax rank, but cant. 

```
query_filename,rank,query_name,query_md5,match_name,match_md5,intersect_bp,lineage
/group/ctbrowngrp/irber/data/wort-data/wort-sra/sigs/DRR149264.sig,0,DRR149264,22f0f1eb6409cb4a18db7d7d6f01191b,"GCF_000210075.1 Bacteroides xylanisolvens XB1A strain=XB1A, ASM21007v1",a4095581bfc3f9140669023861155579,4743,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides xylanisolvens
/group/ctbrowngrp/irber/data/wort-data/wort-sra/sigs/DRR149264.sig,1,DRR149264,22f0f1eb6409cb4a18db7d7d6f01191b,"GCF_000011065.1 Bacteroides thetaiotaomicron VPI-5482 strain=VPI-5482, ASM1106v1",018f0ce73f4369161b26e9bee03b9af2,4237,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides thetaiotaomicron
/group/ctbrowngrp/irber/data/wort-data/wort-sra/sigs/DRR149264.sig,2,DRR149264,22f0f1eb6409cb4a18db7d7d6f01191b,"GCF_000158035.1 Bacteroides cellulosilyticus DSM 14838 strain=DSM 14838, ASM15803v1",658f5f04d15d72a53a232fde83e1ca2e,3966,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides cellulosilyticus
```

**Comment by ctb** [comment]
maybe related issue? https://github.com/sourmash-bio/sourmash/issues/3095#issuecomment-2195722517

**Comment by ctb** [comment]
ok, I think I'm just confused :).

A few questions for you:
* is the command line for `sourmash tax annotate` above correct? it looks suspicious.
* what version of `sourmash_plugin_branchwater` are you using? It should have `f_unique_weighted` in the gather output now if you're using the most recent one, v0.9.5.

Now, on to the question of `tax annotate` - it should give you all the ranks, and then you will need to parse them out yourself by splitting on `;` and popping them off. Right now there's no command-line flag to limit the rank output of `tax annotate`. The `tax metagenome` command has more varied and more flexible output.

**Comment by ctb** [comment]
spoke with @AnneliektH, issue will probably resolved by branchwater update!
