### ISSUE TITLE
Searching against multiple databases with `fastmultigather`

### ISSUE THREAD

**Issue by JiaweiShen1116** [sourmash-bio/sourmash_plugin_branchwater#406]
For `sourmash gather` command, it is possible to search the input sig.gz file against multiple sketch databases by providing the paths to those database files as positional arguments. Is it possible to do the same with `sourmash scripts fastmultigather`? I tried but it seems to only accept one value for the positional argument of database path. Thank you for your help.

**Comment by ctb** [comment]
it is not currently possible, but we are working on it! For now, you would need to concatenate your databases with `sig cat <databases> -o combined.sig.zip`.

**Comment by ctb** [comment]
(leave this open and I will tag you in when we implement this!)

**Comment by ctb** [comment]
This is being implemented in #430 and should be part of the next release, v0.9.8.

**Comment by ctb** [comment]
hi @JiaweiShen1116 this is now available in v0.9.8! The trick is to use `sourmash sig collect *.sig.zip -F csv -o combined.mf.csv` to create a standalone manifest listing all the things you want to search; then `fastmultigather`can load this `combined.mf.csv`. Please let me know if you run into any issues!
