### ISSUE TITLE
Compare fastmultigather `--save-matches` with sourmash search results

### ISSUE THREAD

**Issue by mr-eyes** [sourmash-bio/sourmash_plugin_branchwater#427]
* I would like to compare to the sourmash output somehow; will think on the test

_Originally posted by @ctb in https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/397#issuecomment-2284927139_

**Comment by ctb** [comment]
This was actually added in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/423!
