### ISSUE TITLE
`moltype` needs to be fixed in singlesketch

### ISSUE THREAD

**Issue by mr-eyes** [sourmash-bio/sourmash_plugin_branchwater#462]
wait! no, `moltype` needs to be fixed: the moltype that is needed at the beginning of sketching is actually the input moltype, not the sketch moltype -- i.e. is the FASTA file DNA or protein? I think an --input-moltype param might be needed.

@ctb @mr-eyes 

_Originally posted by @bluegenes in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/459#issuecomment-2384591229_

**Comment by ctb** [comment]
also need to check - can you use multiple ksize in a param string? `k=21,k=31` etc.
